/**
 * GOAL-3 Task 1 — smoke test for the crafted register-family fixture.
 *
 * The fixture is generated by scripts/make-register-sample.ts (committed alongside
 * the .xlsx). Its arithmetic is hand-verified in GOAL-3.md §7 Task 1:
 *   Σ credits 3,675.500 · Σ debits −910.000 · stated EoD 2,730.000 · gap 35.500.
 * Downstream suites (registerParse/statementParse/detect/registerMatch/…) assert
 * the engine-level numbers; this suite only proves the workbook has the real
 * Task-0 header shapes and the designed sums.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { sheetsFromXlsx } from '../../src/lg/ingest';
import { RawRow } from '../../src/shared/models';

const FIXTURE = join(__dirname, '..', 'fixtures', 'lg', 'register-sample.xlsx');

function isBlank(row: RawRow): boolean {
    return row.every((c) => c === null || c === undefined || String(c).trim() === '');
}

describe('register-family fixture', () => {
    let sheets: { name?: string; rows: RawRow[] }[];

    beforeAll(async () => {
        sheets = await sheetsFromXlsx(readFileSync(FIXTURE));
    });

    test('carries the three role sheets with the Task-0 header shapes', () => {
        const names = sheets.map((s) => s.name);
        expect(names).toEqual(expect.arrayContaining(['Credit', 'Debit', 'Sheet1']));

        const credit = sheets.find((s) => s.name === 'Credit')!;
        expect(credit.rows[0]).toEqual(
            expect.arrayContaining([
                'Transaction Date',
                'Posting Date',
                'Nostro/BGL Account',
                'Journal Number',
                'Transaction Credit Amount',
                'Transaction Debit Amount',
                'End Date EoD Balance',
                'Detailed Description',
                'Branch',
            ])
        );
        expect(credit.rows[0][5]).toBe('MGR CHQ Number');

        const debit = sheets.find((s) => s.name === 'Debit')!;
        expect(debit.rows[0][5]).toBe('count');
        expect(debit.rows[0][32]).toBe('reconciled');

        const register = sheets.find((s) => s.name === 'Sheet1')!;
        expect(register.rows[0]).toEqual(
            expect.arrayContaining([
                'etl_date',
                'c6_chq_no',
                'c9_amount',
                'c12_status',
                'c16_issued_date',
                'c17_issued_post_dt',
                'c19_issued_jrnl_no',
                'c25_matchd_post_dt',
                'c27_matchd_jrnl_no',
                'Ops Remark',
                'Ops Journal',
                'Ops Date',
            ])
        );
    });

    test('ledger sums match the hand-verified arithmetic (GOAL-3 Task 1)', () => {
        const credit = sheets.find((s) => s.name === 'Credit')!;
        const debit = sheets.find((s) => s.name === 'Debit')!;
        const creditCol = credit.rows[0].indexOf('Transaction Credit Amount');
        const debitCol = debit.rows[0].indexOf('Transaction Debit Amount');

        const sum = (rows: RawRow[], col: number) =>
            rows
                .slice(1)
                .filter((r) => !isBlank(r))
                .reduce((acc, r) => acc + (typeof r[col] === 'number' ? (r[col] as number) : 0), 0);

        expect(sum(credit.rows, creditCol)).toBeCloseTo(3675.5, 3);
        // Debits are held NEGATIVE in their own column (file §1 convention).
        expect(sum(debit.rows, debitCol)).toBeCloseTo(-910.0, 3);
    });

    test('register carries 11 cheques and blank padding rows', () => {
        const register = sheets.find((s) => s.name === 'Sheet1')!;
        const chqCol = register.rows[0].indexOf('c6_chq_no');
        const dataRows = register.rows.slice(1).filter((r) => !isBlank(r));
        expect(dataRows).toHaveLength(11);
        expect(register.rows.slice(1).some(isBlank)).toBe(true);
        expect(dataRows.map((r) => String(r[chqCol]))).toEqual(
            expect.arrayContaining(['1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '1010', '1011'])
        );
    });
});
